import = ["~/.config/alacritty/themes/alabaster_dark.toml"]

[font]
normal = { family = "FiraMono Nerd Font", style = "Regular" }
size = 25

[window]
startup_mode = "Fullscreen"
decorations_theme_variant = "Dark"

[keyboard]
bindings = [
    { key = "k", mods = "Command", action = "ScrollLineUp" },
    { key = "k", mods = "Command|Shift", action = "ScrollHalfPageUp" },
    { key = "j", mods = "Command", action = "ScrollLineDown" },
    { key = "j", mods = "Command|Shift", action = "ScrollHalfPageDown" },
    { key = "r", mods = "Control", action = "ToggleViMode" },
]

[colors.primary]
background = "#000000"

[colors.normal]
# black = "#000000"
# red = "#be0007"
# green = "#22c505"
# yellow = "#c3c30a"
blue = "#3b84eb"
# magenta = "#bc00c6"
cyan = "#1dc4c1"
# white = "#FFFFFF"

[cursor]
style = { shape = "Block", blinking = "Off" }
